image: maven:latest

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  GPG_TTY: "$(tty)"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test

deploy:
  stage: deploy
  script:
  - gpg --batch --yes --passphrase $GPG_PASS -v --import <(echo "$GPG_PRIVATE_KEY")
  - mvn $MAVEN_CLI_OPTS clean package install -Dmaven.test.skip=true  org.sonatype.plugins:nexus-staging-maven-plugin:deploy  -Prelease -Dgpg.passphrase=$GPG_PASS
